### ISSUE TITLE
[Feature Request] Lock system tray icons size When Resize Panel

### ISSUE THREAD

**Issue by clrizzi** [minios-linux/minios-live#23]
I would like to suggest the possibility of locking the size of the system tray icons when enlarging the other taskbar icons. The system tray icons become disproportionate when, for example, we increase the size of the panel. 

It could be similar behavior to what we see in Zorin OS Xfce.

**Comment by FershoUno** [comment]
Hello, you just need to configure the desired panel, select the "Appearance" option, in the "Icons" part and enable the "automatically resize" option

I attach a screenshot, by the way I speak Spanish so the version I use is for my language
![photo_2024-01-02_22-45-50](https://github.com/minios-linux/minios-live/assets/50505848/4a57a7b2-6239-4f68-9452-e6b0194900e7)
