### ISSUE TITLE
MiniOS installer via graphic 

### ISSUE THREAD

**Issue by NascaED** [minios-linux/minios-live#26]
The MiniOS system is amazing and would you like to know about the future of the MiniOS system installer? There are reports of some users having problems with the installation because they are forgetting to change the minios.conf file before booting for the first time after installation. The system's graphical installer can alert with a modal so that they are reminded to make changes to the minios.conf file or the installer itself can release these fields in a graphical way to facilitate the user and attract more people to the community.

**Comment by crim50n** [comment]
For now, we have very different goals in development.
