### ISSUE TITLE
How to install for real without squashfs..

### ISSUE THREAD

**Issue by tbone2k-git** [minios-linux/minios-live#28]
Hello! o)

I'm looking for a distro like MiniOS (small, no bloat, just required basics), but I need it installed for real, not on USB drive.
Is there any chance this can be done with MiniOS (avoiding squashfs as well)?

The other popular distros offer full installation only with 10gb+ in size or no desktop/functionality at all. For some reason there is no sensible middle ground distro regarding size. Yours looks perfect! I guess it also does not include locale data for every language on earth, all the man pages or 900mb of fonts like all the other distros, gosh! o) I have several smaller clients with 2gb SSD which I'd like to get up and running. I did my own mini-debian setup in around 200-400mb in size, using btrfs compression with full desktop and audio, but my scripts don't work anymore with debian12. I don't really like to start from scratch! o)

If you tell me, MiniOS cannot be installed to hdd/sdd.. that would be sad. Is there something else out there you know of, that is same size and is meant to be used with internal ssd / hardrive?

Thank you and have a nice day! o)

**Comment by crim50n** [comment]
MiniOS can be installed on an HDD, but only in the same way as a flash drive. The system will not work in "raw" form.
