### ISSUE TITLE
How to boot from .iso with grub2 and gru4dos?

### ISSUE THREAD

**Issue by JeanCarloEM** [minios-linux/minios-live#34]
Please, as a project intended for use directly on a USB stick, and considering its usefulness on a Swiss Army Knife USB stick, it is very useful to be able to boot from the .iso file in loopback with grub2 and grub4dos, but this doesn't seem to work. work for this project.

**Comment by crim50n** [comment]
Try this solution
https://github.com/minios-linux/minios-live/issues/45#issuecomment-2311243912
