### ISSUE TITLE
A big problem

### ISSUE THREAD

**Issue by Ilyaviznitsa** [minios-linux/minios-live#35]
I was trying to boot up to minios, i loaded to boot menu but i can't boot into the system.
Automatic is boot not working
Resume previous session, Start a new session and Choose session during startup is not working!
I used a virtualbox to use it...
This is a virtualbox problem or problem with MiniOS?
Video about this
https://cloud.mail.ru/public/VpbG/FGKexQXVG

**Comment by crim50n** [comment]
Did you install the system on a virtual disk or is it a run from an iso image?

**Comment by Ilyaviznitsa** [comment]
I runned from an iso image

**Comment by crim50n** [comment]
> I runned from an iso image

If your virtual machine is using default settings then the problem may be a faulty iso, try downloading it again. What edition are you using?

**Comment by Ilyaviznitsa** [comment]
Ultra Edition

**Comment by crim50n** [comment]
In VitrualBox, all editions of MiniOS version 3+ should work without problems. If you still have not managed to solve the problem, write to our Telegram chat (address is on the website), we can help you quickly.

**Comment by Ilyaviznitsa** [comment]
I forgot to mention that also i have this error
![image](https://github.com/minios-linux/minios-live/assets/117360468/3e442ed5-e7d2-4842-8e51-62d77dac6bd6)

**Comment by Ilyaviznitsa** [comment]
Problem Solved!
Reason of issue: Not so much of RAM
(In VM i haved a 64MB of RAM)
