### ISSUE TITLE
Cant switch to full install

### ISSUE THREAD

**Issue by yw4z** [minios-linux/minios-live#37]
Looks like a great balanced distro but i cant book into full install. its always working as live cd even on HDD
used install menu and removed virtual disk. checked boot options. working only as live cd a planned feature ?

btw i'm using this image
minios-bookworm-xfce-standard-en-lkm-aufs-amd64-zstd-20240102_0508

**Comment by crim50n** [comment]
Install the distribution using these instructions:
https://github.com/minios-linux/minios-live/wiki/Install-MiniOS-on-hard-disk-or-USB-flash-drive

**Comment by yw4z** [comment]
thanks will check that

**Comment by crim50n** [comment]
If you are using Windows, you can install with Rufus using the default settings.

**Comment by yw4z** [comment]
just testing on virtual machine right now. trying to find a home for klipper software. i need really low storage and ram usage

**Comment by crim50n** [comment]
then you need to create a SATA type virtual disk in a virtual machine and then use MiniOS Installer to install it

**Comment by crim50n** [comment]
It looks like you were creating a SCSI disk, which caused the virtual machine to boot from the iso again instead of from the disk

**Comment by yw4z** [comment]
installed to hdd on vm but after booting without iso vm shows no boot option for miniOS.
ofc removed iso before boot
miniOS files exist on hdd after install but its not booting to it

**Comment by crim50n** [comment]
Send a screenshot of your virtual machine configuration please

**Comment by yw4z** [comment]
Sorry about different language on VM

![Screenshot-20240608120528](https://github.com/minios-linux/minios-live/assets/28517890/f65a090c-4814-42a2-834d-ecf3302d6962)
![Screenshot-20240608120557](https://github.com/minios-linux/minios-live/assets/28517890/d09d43b4-ba95-4a85-b461-30a512315316)
![Screenshot-20240608120827](https://github.com/minios-linux/minios-live/assets/28517890/e1796610-14c6-4649-90d5-3e91298d47d2)

After reboot install menu still exist and minios still in live CD mode. there is no iso connected
![Screenshot-20240608121033](https://github.com/minios-linux/minios-live/assets/28517890/85292463-a6af-4191-964b-befb163e96d2)

**Comment by crim50n** [comment]
That's right, it should work. But I suggest you try using ext4. And if your virtual machine uses EFI, you should check the box in the installer.
