### ISSUE TITLE
Cannot install Minios tp EMMC. 

### ISSUE THREAD

**Issue by curyjorge98** [minios-linux/minios-live#39]
Hi people,

I want to install Mini OS in my Beelink T4 Mini PC but install procedure does not give me the option to write to EMMC or sdcard (/dev/mmcblk0).

Rufus doesn`t run on Linux, Tryed etcher and gnome-disk-utility but not good idea... dd must be a mistake too.

That sda on the screenshot is my Ventoy drive I'm using to boot Mini OS.

Please make install give me the correct option: /dev/mmcblk0.

**Comment by curyjorge98** [comment]
The pic is here...

![Captura de tela_2024-07-14_01-32-46](https://github.com/user-attachments/assets/e01246cd-b0af-4432-9877-32578188b143)

**Comment by crim50n** [comment]
Fixed in 3.3.4.
