### ISSUE TITLE
无法通过grub2和iventoy启动iso文件

### ISSUE THREAD

**Issue by Sirius2016** [minios-linux/minios-live#40]
grub命令行启动iso文件：

set iso_path="/minios.iso"
loopback iso_root $iso_path
linux (iso_root)/minios/boot/vmlinuz boot=minios iso-scan/filename=$iso_path
initrd (iso_root)/minios/boot/initrd.img
boot

具体报错截图：
![image](https://github.com/user-attachments/assets/02ab1336-753f-470a-a765-f7fec8a54a5d)

我测试使用iventoy从网络pxe启动也是报上图一样的错误。

Grub command line to start iso file:
set iso_path="/minios.iso"
loopback iso_root $iso_path
linux (iso_root)/minios/boot/vmlinuz boot=minios iso-scan/filename=$iso_path
initrd (iso_root)/minios/boot/initrd.img
boot

Specific error screenshot:
![image](https://github.com/user-attachments/assets/02ab1336-753f-470a-a765-f7fec8a54a5d)

I tested using iventoy to boot from network PXE, but it also reported the same error as shown in the picture.

**Comment by Sirius2016** [comment]
好像是.sb模块文件无法加载成功。

It seems that the. sb module file could not be loaded successfully.

**Comment by crim50n** [comment]
Thanks for the info, I will try to check the MiniOS functionality in iventoy.

**Comment by crim50n** [comment]
Try this solution
https://github.com/minios-linux/minios-live/issues/45#issuecomment-2311243912
