### ISSUE TITLE
No desktop in latest flux-minimum v3.3.4

### ISSUE THREAD

**Issue by pigeonskiller** [minios-linux/minios-live#43]
Tested in Virtual Machine Manager.
No desktop in latest flux-minimum v3.3.4: the boot sequence stops with a tty asking login and password.
And startx from tty does not work.

**Comment by crim50n** [comment]
> Tested in Virtual Machine Manager. No desktop in latest flux-minimum v3.3.4: the boot sequence stops with a tty asking login and password. And startx from tty does not work.

Thank you very much for the bug report, I will check if the image works.

**Comment by pigeonskiller** [comment]
Thank you. Now it works well. ;-)
