### ISSUE TITLE
Boot parameter "from="

### ISSUE THREAD

**Issue by LinuxWelt** [minios-linux/minios-live#45]
I was wondering if the boot parameter

`from=`

could be made to work as in Slax, in order to boot ISO files directly via loopback.
Currently, MiniOS does not find its own filesystem when booted from its ISO using this parameter - unlike Slax.

Best regards

![screenshot_20240820_101808](https://github.com/user-attachments/assets/06a816cd-dd4a-41c2-83b4-cb61bc5a7f7c)

**Comment by crim50n** [comment]
Describe in more detail, please. I checked on version 3.3.4, everything works as it should.

![image](https://github.com/user-attachments/assets/7647dc4f-5c70-461b-b76f-732af746e2f2)

**Comment by LinuxWelt** [comment]
Hi crimS0n,
thank you for your swift reply. I now believe that the difference to Slax in treating the boot option "from=" is the provided path. When I just provide a (relative) path on the boot media ISO-9660 hybrid image in my case, then MiniOS doesn't find its own ISO. 

Example, the tested entry in a Grub 2.12 boot menu:

```
menuentry "Mini OS 3.3.4 Test" {
  loopback loop /ISO-Files/minios334.iso
    linux (loop)/minios/boot/vmlinuz quiet from=/ISO-Files/minios334.iso load_ramdisk=1 prompt_ramdisk=0 noauto printk.time=0 consoleblank=0 net.ifnames=0 biosdevname=0 minios.flags=  
    initrd (loop)/minios/boot/initrfs.img
  }
```

It seems that MiniOS requires a device ID for ¨from=" like in your given example.

**Comment by crim50n** [comment]
This works for me:
```
menuentry "Run MiniOS (Fresh start)" {
    set isofile="/Image-Dateien/minios-bookworm-xfce-standard-de-lkm-aufs-amd64-zstd-20240827_0130.iso"
    loopback loop ${isofile}
    echo "Loading MiniOS from ${isofile}"
    linux (loop)/minios/boot/vmlinuz load_ramdisk=1 prompt_ramdisk=0 rw printk.time=0 consoleblank=0 net.ifnames=0 biosdevname=0 quiet from=${isofile}
    initrd (loop)/minios/boot/initrfs.img
}
```
An example of a working image:
https://drive.google.com/file/d/1tGhgETyy2lWywnRljPJqwunVCYJ4GnVw/view?usp=drive_link
