### ISSUE TITLE
minios can't detect network interface

### ISSUE THREAD

**Issue by destaa** [minios-linux/minios-live#47]
i'm new in minios
in first try, there is no network device available in network system tray
checked ifconfig, show lo loopback only
checked /etc/udev/rules.d, empty
checked /etc/network/interfaces, empty
checked /etc/network/interfaces.d, empty

what is wrong?

**Comment by crim50n** [comment]
What edition of MiniOS are you using?

**Comment by destaa** [comment]
newest version of minios, i chose maximum edition

let me tell you
first i tried newest slax debian and newest minios maximum.
only minios that has problem with network interface
BUT, both of them has problem with acpi bios error upon shuting down
after updating bios, the problem is solved

i tried both of them again, and now both of them has problem with network interface

what is wrong with that? is it because the bios?

**Comment by destaa** [comment]
nevermind

wlan0 interface appeared after creating new sessions several times

is it bug? but why slax produce same issue?

anyway you can close this
