### ISSUE TITLE
Unable to mount sda1/

### ISSUE THREAD

**Issue by nebx1** [minios-linux/minios-live#49]
I'm new to linux and trying out new operating systems.
not sure why this message keeps coming "Unable to mount sda1/".
and also I'm using a virtual box.

**Comment by FershoUno** [comment]
Hello, how did you perform the installation?

**Comment by nebx1** [comment]
as an .iso image from the website 
downloaded the Flux one

**Comment by nebx1** [comment]
and yes i did use the integrated installer.

**Comment by FershoUno** [comment]
Hello, sorry for the delay

I just tried MiniOS FLux 64-bit edition, it works fine in VirtualBox, I might recommend you try to reinstall it

**Comment by FershoUno** [comment]
If it doesn't work after reinstallation, could you tell me the virtual machine settings?

**Comment by nebx1** [comment]
Hey btw I just tried the standard version and it worked perfectly fine!! And also does the "install minios" file won't go away even after installing the os? And also does the user named "live"  automatically created?

**Comment by nebx1** [comment]
And yes I will reinstall the virtualbox

**Comment by FershoUno** [comment]
it was not necessary to reinstall VirtualBox, but
to reinstall MiniOS (inside the virtual machine)

**Comment by FershoUno** [comment]
Yes, by default the user credentials are:

live:evil
root:root

If you want to change some things, you can read this "Configuration File" guide

https://github.com/minios-linux/minios-live/wiki/Configuration-file

**Comment by nebx1** [comment]
oh okay i will do that also, can I use this operating system for development purpose since i got a scrappy device i have to run some programs without any issues.

**Comment by nebx1** [comment]
I did try to install but it still shows the same error "Failed to remove mount point mnt/install/sda1"

**Comment by FershoUno** [comment]
Yes, you can use MiniOS for whatever you want
In my opinion, MiniOS ultra has tools like docker, VirtManager, Codium, among other tools pre-installed to use it
