### ISSUE TITLE
Audio Dummy Output INTEL thesofproject sof FIRMWARE NOT INCLUDED

### ISSUE THREAD

**Issue by snjvm** [minios-linux/minios-live#51]
Hello Team,
I downloaded minios-bookworm-xfce-maximum-en-lkm-aufs-amd64-zstd-20240815_0729.iso and liveboot through Ventoy. Audio is not working. Output Devices shows **Dummy Output**. Searched Google for resolution and found out **Intel sof Firmware** not available on ISO. Please [include](https://github.com/thesofproject/sof) them. Thanks.
I have HP ProBook 440 G7 with Audio:
  Device-1: Intel Comet Lake PCH-LP cAVS vendor: Hewlett-Packard
    driver: **sof-audio-pci-intel-cnl**
    alternate: snd_hda_intel,snd_sof_pci_intel_cnl bus-ID: 00:1f.3
    chip-ID: 8086:02c8 class-ID: 0401

**Comment by crim50n** [comment]
Added driver to new version of MiniOS.
