### ISSUE TITLE
How can I update the system without losing all my data?

### ISSUE THREAD

**Issue by MiguelSanzBr** [minios-linux/minios-live#57]
I want to update to version v4.0.0, but I don't want to lose my data, is it possible?

**Comment by crim50n** [comment]
Only manually, if you know how to do it. Implementing the update mechanism in a modular system is too time-consuming a task for which we do not yet have the resources.

**Comment by MiguelSanzBr** [comment]
ok, I understand, but how could I perform this update manually?

**Comment by crim50n** [comment]
As I wrote above, if you know how to do it. This is a very complex operation requiring Linux administrator level skills.
